[package]
name = "duckchess"
version = "0.0.0"
edition = "2021"
description = ""

[lib]
crate-type = []
path = "main.rs"

[dependencies.duckchess-fluvio]
path = "fluvio/packages/duckchess-fluvio/rust/duckchess-fluvio"

[dependencies.duckchess-server]
path = "gameserver"
