[package]
name = "duckchess-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
ws = { package = "rocket_ws", version = "0.1.1" }
serde = "1.0.216"
